# Generated by Django 4.1.5 on 2023-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
